/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Home constants for all features.
 */
export class HomeConstants {
  /**
   * Constants on the tab page of the main interface.
   */
  static readonly CURRENT_INDEX: number = 0;
  static readonly TAB_BAR_FIRST: number = 0;
  static readonly TAB_BAR_SECOND: number = 1;
  static readonly BAR_WIDTH: number = 360;
  static readonly BAR_HEIGHT: number = 60;
  static readonly FONT_WEIGHT_SELECT: number = 500;
  static readonly FONT_WEIGHT_UNSELECT: number = 400;
  static readonly LINE_HEIGHT: number = 22;
  static readonly MARGIN_TOP_TWO: number = 17;
  static readonly MARGIN_BOTTOM: number = 7;
  static readonly STROKE_WIDTH: number = 2;
  /**
   * Constant of the video list.
   */
  static readonly COLUMN_WIDTH: string = '86.7%';
  static readonly LIST_SPACE: number = 20;
  static readonly LIST_INITIAL_INDEX: number = 0;
  static readonly IMAGE_HEIGHT: string = '84.8%';
  static readonly IMAGE_WIDTH: string = '26.7%';
  static readonly DIVIDER_STROKE_WIDTH: number = 1;
  static readonly LIST_ITEM_ROW_COLUMN_WIDTH: string = '73.3%';
  static readonly LIST_ITEM_ROW_HEIGHT: string = '12.3%';
  static readonly WIDTH: number = 720;
  static readonly HEIGHT: number = 720;
  /**
   * Scan local video and add network video buttons.
   */
  static readonly TAB_BUTTON_HEIGHT: string = '51%';
  static readonly TAB_COLUMN_HEIGHT: string = '10%';
  /**
   * Add Network Video dialog box.
   */
  static readonly OFFSET_DX: number = 0;
  static readonly OFFSET_DY: number = -20;
  static readonly GRID_COUNT: number = 4;
  static readonly TEXT_HEIGHT: string = '6.7%';
  static readonly TEXT_MARGIN_TOP: string = '3.1%';
  static readonly DURATION: number = 1000;
  static readonly DURATION_ONE: number = -1;
  static readonly DURATION_TWO: number = 0;
}