/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
const LinkData: any[] = [
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 1,
    "courseName": "应用市场介绍",
    "imageUrl": "/image/image1.jpg",
    "price": 0
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 2,
    "courseName": "上架流程",
    "imageUrl": "/image/image2.jpg",
    "price": 100
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 3,
    "courseName": "应用出海",
    "imageUrl": "/image/image3.jpg",
    "price": 50
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 4,
    "courseName": "审核政策",
    "imageUrl": "/image/image4.jpg",
    "price": 222
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 5,
    "courseName": "CaaS Kit - HMS Core精品实战课",
    "imageUrl": "/image/image5.jpg",
    "price": 256
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 6,
    "courseName": "机器学习在图像分割场景中的应用",
    "imageUrl": "/image/image6.jpg",
    "price": 0
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 7,
    "courseName": "一分钟了解华为应用内支付服务",
    "imageUrl": "/image/image7.png",
    "price": 0
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 8,
    "courseName": "一分钟了解华为位置服务",
    "imageUrl": "/image/image8.png",
    "price": 400
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 9,
    "courseName": "Excel函数在商业中的应用",
    "imageUrl": "/image/image9.png",
    "price": 65
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 10,
    "courseName": "“震动”手机锁屏制作",
    "imageUrl": "/image/image10.png",
    "price": 0
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 11,
    "courseName": "“流体动效”手机锁屏制作",
    "imageUrl": "/image/image11.png",
    "price": 50
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 12,
    "courseName": "HUAWEI GT自定义表盘制作",
    "imageUrl": "/image/image12.jpg",
    "price": 70
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 13,
    "courseName": "商务表盘制作",
    "imageUrl": "/image/image13.jpg",
    "price": 0
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 14,
    "courseName": "5分钟了解跨应用、跨形态无缝登录",
    "imageUrl": "/image/image14.jpg",
    "price": 80
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 15,
    "courseName": "oCPC进阶功能及最新政策解读",
    "imageUrl": "/image/image15.png",
    "price": 120
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 16,
    "courseName": "HUAWEI Ads 游戏行业投放指南",
    "imageUrl": "/image/image16.png",
    "price": 160
  },
  {
    "superId": 3,
    "superName": "HarmonyOS",
    "id": 17,
    "courseName": "HarmonyOS物联网开发课程",
    "imageUrl": "/image/image17.jpg",
    "price": 1020
  },
  {
    "superId": 3,
    "superName": "HarmonyOS",
    "id": 18,
    "courseName": "【Hello系列直播课】第1期：手把手教你搭建开发环境",
    "imageUrl": "/image/image18.png",
    "price": 0
  },
  {
    "superId": 3,
    "superName": "HarmonyOS",
    "id": 19,
    "courseName": "HarmonyOS技术训练营-10分钟快速体验HarmonyOS分布式应用",
    "imageUrl": "/image/image19.jpg",
    "price": 0
  },
  {
    "superId": 3,
    "superName": "HarmonyOS",
    "id": 20,
    "courseName": "应用开发基础：JS FA开发基础（第一期）",
    "imageUrl": "/image/image20.jpg",
    "price": 0
  },
  {
    "superId": 3,
    "superName": "HarmonyOS",
    "id": 21,
    "courseName": "HarmonyOS Connect设备开发基础：OpenHarmony基础",
    "imageUrl": "/image/image21.jpg",
    "price": 60
  },
  {
    "superId": 3,
    "superName": "HarmonyOS",
    "id": 22,
    "courseName": "组件开发和集成：SDK集成指南（第五期）",
    "imageUrl": "/image/image22.jpg",
    "price": 120
  },
  {
    "superId": 4,
    "superName": "精彩活动",
    "id": 23,
    "courseName": "HUAWEI Developer Day•2018北京精彩回顾",
    "imageUrl": "/image/image23.jpg",
    "price": 0
  },
  {
    "superId": 4,
    "superName": "精彩活动",
    "id": 24,
    "courseName": "华为AR帮你轻松打造酷炫应用",
    "imageUrl": "/image/image24.jpg",
    "price": 99
  },
  {
    "superId": 4,
    "superName": "精彩活动",
    "id": 25,
    "courseName": "ARVR应用创新大赛获奖作品",
    "imageUrl": "/image/image25.jpg",
    "price": 30
  },
  {
    "superId": 4,
    "superName": "精彩活动",
    "id": 26,
    "courseName": "华为HiLink智能家居生态介绍",
    "imageUrl": "/image/image26.jpg",
    "price": 80
  },
  {
    "superId": 4,
    "superName": "精彩活动",
    "id": 27,
    "courseName": "华为校园千帆行丨武汉站",
    "imageUrl": "/image/image27.jpg",
    "price": 160
  },
  {
    "superId": 4,
    "superName": "精彩活动",
    "id": 28,
    "courseName": "HUAWEI Developer Day•杭州站精彩回顾",
    "imageUrl": "/image/image28.jpg",
    "price": 0
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 29,
    "courseName": "优秀实践分享 - 掌阅科技",
    "imageUrl": "/image/image29.jpg",
    "price": 0
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 30,
    "courseName": "极限试驾",
    "imageUrl": "/image/image30.png",
    "price": 130
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 31,
    "courseName": "AR狙击手",
    "imageUrl": "/image/image31.png",
    "price": 100
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 32,
    "courseName": "宇宙解码",
    "imageUrl": "/image/image32.png",
    "price": 100
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 33,
    "courseName": "Wars of Stone",
    "imageUrl": "/image/image33.png",
    "price": 1200
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 34,
    "courseName": "ROCK ME",
    "imageUrl": "/image/image34.png",
    "price": 156
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 35,
    "courseName": "神奇AR智能宝宝",
    "imageUrl": "/image/image35.png",
    "price": 130
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 36,
    "courseName": "从零开始学架构",
    "imageUrl": "/image/image36.jpg",
    "price": 120
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 37,
    "courseName": "架构设计之异步化技术",
    "imageUrl": "/image/image37.jpg",
    "price": 0
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 38,
    "courseName": "架构设计之页面静态化技术",
    "imageUrl": "/image/image38.jpg",
    "price": 0
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 39,
    "courseName": "Python极简入门",
    "imageUrl": "/image/image39.jpg",
    "price": 0
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 40,
    "courseName": "Python实践指南",
    "imageUrl": "/image/image40.jpg",
    "price": 2001
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 41,
    "courseName": "Java高级特性",
    "imageUrl": "/image/image41.jpg",
    "price": 30
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 42,
    "courseName": "C++核心编程",
    "imageUrl": "/image/image42.jpg",
    "price": 50
  },
  {
    "superId": 7,
    "superName": "移动开发",
    "id": 43,
    "courseName": "EMUI 9.1主题转10.0主题适配指导",
    "imageUrl": "/image/image43.png",
    "price": 0
  },
  {
    "superId": 7,
    "superName": "移动开发",
    "id": 44,
    "courseName": "“流体动效”手机锁屏制作",
    "imageUrl": "/image/image44.png",
    "price": 0
  },
  {
    "superId": 7,
    "superName": "移动开发",
    "id": 45,
    "courseName": "“震动”手机锁屏制作",
    "imageUrl": "/image/image45.png",
    "price": 0
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 46,
    "courseName": "DevOps新技术入门",
    "imageUrl": "/image/image46.png",
    "price": 50
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 47,
    "courseName": "Vue.js 框架开发系列课程",
    "imageUrl": "/image/image47.jpg",
    "price": 60
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 48,
    "courseName": "jQuery实例精讲",
    "imageUrl": "/image/image48.png",
    "price": 80
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 49,
    "courseName": "JavaScript 编程技巧与实战",
    "imageUrl": "/image/image49.jpg",
    "price": 300
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 50,
    "courseName": "基于 Bootstrap 框架开发技巧实战",
    "imageUrl": "/image/image50.jpg",
    "price": 150
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 51,
    "courseName": "Java Web开发课程",
    "imageUrl": "/image/image51.jpg",
    "price": 200
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 52,
    "courseName": "JavaScript 设计模式",
    "imageUrl": "/image/image52.jpg",
    "price": 0
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 53,
    "courseName": "HTML入门基础系列课程",
    "imageUrl": "/image/image53.jpg",
    "price": 0
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 54,
    "courseName": "前端系列第7期-微前端–架构介绍篇",
    "imageUrl": "/image/image54.png",
    "price": 100
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 55,
    "courseName": "Web安全系列课程",
    "imageUrl": "/image/image55.png",
    "price": 0
  }
]

export class TabItem {
  position: number; // 点击该分类时课程内容滑动到的位置
  superName: string; // 课程分类标题

  constructor(position: number, superName: string) {
    this.position = position;
    this.superName = superName;
  }
}

export class CourseItem {
  tag: boolean; // 是否此类别课程的头部
  index: number; // 课程所对应课程类别的索引位置
  courseName: string; // 课程名称
  imageUrl: string; // 图片地址
  price: number; // 价格

  constructor(tag: boolean, index: number, courseName: string, imageUrl: string, price: number) {
    this.tag = tag;
    this.index = index;
    this.courseName = courseName;
    this.imageUrl = imageUrl;
    this.price = price;
  }
}

export class LinkDataItem {
  tabArray: Array<TabItem> = [] // 课程分类数据
  listArray: Array<CourseItem> = [] // 课程数据

  constructor(tabArray: Array<TabItem>, listArray: Array<CourseItem>) {
    this.tabArray = tabArray;
    this.listArray = listArray;
  }
}

export function getLinkData(): LinkDataItem {
  let linkDataItem = new LinkDataItem([],[]);
  let superId: number = 0
  LinkData.forEach(item => {
    // 根据数据的superId是否不一样判断是否需要将一级分类添加到数组tabArray中
    if (superId != item.superId) {
      // 添加课程类别
      let tabItem = new TabItem(linkDataItem.listArray.length, item.superName);
      linkDataItem.tabArray.push(tabItem)
      // 添加课程类别头部
      let courseItem = new CourseItem(true, linkDataItem.tabArray.length - 1, item.superName, '', 0);
      linkDataItem.listArray.push(courseItem)
    }

    // 添加课程数据
    let courseItem = new CourseItem(false, linkDataItem.tabArray.length - 1, item.courseName, item.imageUrl, item.price);
    linkDataItem.listArray.push(courseItem)

    superId = item.superId
  })
  return linkDataItem;
}