/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Color constants for all Component.
 */
export default class ColorConstants {
  /**
   * Flower out color.
   */
  static readonly FLOWER_OUT_COLOR: string = '#ED6E21';

  /**
   * Flower inner color.
   */
  static readonly FLOWER_INNER_COLOR: string = '#F8A01E';

  /**
   * Out circle color.
   */
  static readonly OUT_CIRCLE_COLOR: string = '#F7CD03';

  /**
   * White_color.
   */
  static readonly WHITE_COLOR: string = '#FFFFFF';

  /**
   * Inner circle color.
   */
  static readonly INNER_CIRCLE_COLOR: string = '#F8A01E';

  /**
   * Arc pink color.
   */
  static readonly ARC_PINK_COLOR: string = '#FFC6BD';

  /**
   * Arc yellow color.
   */
  static readonly ARC_YELLOW_COLOR: string = '#FFEC90';

  /**
   * Arc green color.
   */
  static readonly ARC_GREEN_COLOR: string = '#ECF9C7'

  /**
   * Text color.
   */
  static readonly TEXT_COLOR: string = '#ED6E21';
}