/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const GET_UP: string = '早起';
export const DRINK: string = '喝水';
export const APPLE: string = '吃苹果';
export const SMILE: string = '每日微笑';
export const BRUSH_TEETH: string = '每日刷牙';
export const SLEEP: string = '早睡';
export const TASK_NAME: string = '任务名称';
export const TASK_TARGET: string = '任务目标';
export const TASK_PROGRESS: string = '任务进度';
export const FREQUENCY: string = '任务频率';
export const REMIND_TIME: string = '提醒时间';
export const EVERYDAY: string = '每天';