/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class LiveConstants {
  /**
   * The width percentage setting.
   */
  static readonly FULL_WIDTH_PERCENT: string = '100%';

  /**
   * The height percentage setting.
   */
  static readonly FULL_HEIGHT_PERCENT: string = '100%';

  /**
   * The font family of title.
   */
  static readonly LIVE_TITLE_FONT_FAMILY: string = 'HarmonyHeiTi-Bold';

  /**
   * Default current breakpoint.
   */
  static readonly CURRENT_BREAKPOINT: string = 'sm';

  /**
   * The font family of live title.
   */
  static readonly LIVE_ITEM_TITLE_FONT_FAMILY: string = 'HarmonyHeiTi-Medium';

  /**
   * The font family of live introduction.
   */
  static readonly LIVE_ITEM_INTRODUCTION_FONT_FAMILY: string = 'HarmonyHeiTi';

  /**
   * The font weight of title.
   */
  static readonly TITLE_FONT_WEIGHT: number = 700;

  /**
   * Four column width.
   */
  static readonly FOUR_COLUMN: number = 4;

  /**
   * Eight column width.
   */
  static readonly EIGHT_COLUMN: number = 8;

  /**
   * Twelve column width.
   */
  static readonly TWELVE_COLUMN: number = 12;

  /**
   * Six column width.
   */
  static readonly SIX_COLUMN: number = 6;

  /**
   * Zero column width.
   */
  static readonly ZERO_COLUMN: number = 0;

  /**
   * One column width.
   */
  static readonly ONE_COLUMN: number = 1;

  /**
   * Four column width.
   */
  static readonly TWO_COLUMN: number = 2;

  /**
   * The font weight of live title.
   */
  static readonly LIVE_TITLE_FONT_WEIGHT: number = 500;

  /**
   * The font weight of live introduction.
   */
  static readonly LIVE_INTRODUCTION_FONT_WEIGHT: number = 400;

  /**
   * The width of small devices.
   */
  static readonly SMALL_DEVICE_TYPE: string = '320vp';

  /**
   * The width of middle devices.
   */
  static readonly MIDDLE_DEVICE_TYPE: string = '600vp';

  /**
   * The width of large devices.
   */
  static readonly LARGE_DEVICE_TYPE: string = '840vp';
}