/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum AppColor {

  // app primary color
  ThemeColor = "#f1f3f5",

  // app secondary color
  ThemeColor2= "#2788d9",

  // background color
  Background = "#f1f3f5",
  Background1 = "#fff",

  //the split line color
  Line = "#f1f3f5",

  // title color
  Title = "#212121",

  // text information description color,such as news release date,author
  Description = "#b4b4b4",

  //text color
  Text = "#424242",

  //Highlight color be used to accent elements,such as URL links
  Highlight = "#0959f7",
  Highlight2 = "#0959f7",

  //component shadow color
  Shadow= "#ececec",

  //warning color
  Warning="#F9CF93"

}



