/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Thousandth
export const THOUSANDTH_80: string = '8%';
export const THOUSANDTH_100: string = '10%';
export const THOUSANDTH_400: string = '40%';
export const THOUSANDTH_500: string = '50%';
export const THOUSANDTH_560: string = '56%';
export const THOUSANDTH_800: string = '80%';
export const THOUSANDTH_900: string = '90%';
export const THOUSANDTH_940: string = '94%';
export const THOUSANDTH_1000: string = '100%';

export const DEFAULT_2: number = 2;
export const DEFAULT_8: number = 8;
export const DEFAULT_12: number = 12;
export const DEFAULT_10: number = 10;
export const DEFAULT_16: number = 16;
export const DEFAULT_18: number = 18;
export const DEFAULT_20: number = 20;
export const DEFAULT_24: number = 24;
export const DEFAULT_28: number = 28;
export const DEFAULT_32: number = 32;
export const DEFAULT_48: number = 48;
export const DEFAULT_56: number = 56;
export const DEFAULT_60: number = 60;

// list space
export const LIST_ITEM_SPACE: number = 2;

// navigation title
export const ADD_TASK_TITLE: string = '添加任务';
export const EDIT_TASK_TITLE: string = '编辑任务';

// prompt message
export const SETTING_FINISHED_MESSAGE = '设置完成！！！';
export const CHOOSE_TIME_OUT_RANGE: string = '选择时间超出范围';

// date format
export const TODAY: string = new Date().toDateString();

// time range
export const DEFAULT_TIME: string = '08:00';
export const GET_UP_TIME_RANGE: string = '(06:00 - 09:00)';
export const SLEEP_TIME_RANGE: string = '(20:00 - 23:00)';
export const GET_UP_EARLY_TIME: string = '06:00';
export const GET_UP_LATE_TIME: string = '09:00';
export const SLEEP_EARLY_TIME: string = '20:00';
export const SLEEP_LATE_TIME: string = '23:00';
export const DEFAULT_SELECTED_TIME: Date = new Date(`${TODAY} 8:00:00`);

// frequency Dialog
export const EVERYDAY: string = '每天';
export const NO_LENGTH: number = 0;
export const INIT_WEEK_IDS: string = '1, 2, 3, 4, 5, 6, 7';

// unit
export const PER_DAY: string = '/ 天';

// offset
export const ZERO: number = 0;
export const MINUS_20: number = -20;
export const HAS_NO_INDEX: number = -1;

// targetSetting Range
export const DRINK_STEP: number = 25;
export const DRINK_MAX_RANGE: number = 500;
export const TIMES_100: number = 100;
export const EAT_APPLE_RANGE: number = 100;
export const DEFAULT_TEXT: string = '0.25';
export const DEFAULT_APPLE: string = '1';

