/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const SWIPER_VIDEOS: object[] = [
  {
    "image": $r("app.media.banner1")
  },
  {
    "image": $r("app.media.banner2")
  },
  {
    "image": $r("app.media.banner3")
  }
];

export const HORIZONTAL_VIDEOS: object[] = [
  {
    "id": 1,
    "image": $r("app.media.video_list0"),
    "name": '视频1'
  },
  {
    "id": 2,
    "image": $r("app.media.video_list1"),
    "name": '视频2'
  },
  {
    "id": 3,
    "image": $r("app.media.video_list2"),
    "name": '视频3'
  }
];