/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class AppConstants {

  /**
   * 100 percent.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * 20 percent.
   */
  static readonly TAB_PERCENT: string = '20%';

  /**
   * Tab bar font weight.
   */
  static readonly TAB_FONT_WEIGHT: number = 600;

  /**
   * Default status height
   */
  static readonly DEFAULT_STATUS_HEIGHT: number = 32;
}