/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class Constants {

  /**
   * 100 percent
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
  * pixel conversion
  */
  static readonly PIXEL_CONVERSION: string = '像素转换';

  /**
  * pixel introduction
  */
  static readonly PIXEL_INTRODUCTION: string = '像素介绍';

  /**
   * IntroductionPage URL
   */
  static readonly INTRODUCTION_PAGE_URL: string = 'pages/IntroductionPage';

  /**
   * ConversionPage URL
   */
  static readonly CONVERSION_PAGE_URL: string = 'pages/ConversionPage';

  /**
   * vp size
   */
  static readonly INDEX_PAGE_TAG: string = 'IndexPage push error ';

  /**
   * font weight 500
   */
  static readonly TITLE_FONT_WEIGHT: number = 500;

  /**
   * font weight 400
   */
  static readonly LABEL_FONT_WEIGHT: number = 400;

  /**
   * column space
   */
  static readonly COLUMN_SPACE: number = 24;

  /**
   * item space
   */
  static readonly ITEM_PADDING: number = 12;

  /**
   * large font size
   */
  static readonly LARGE_FONT_SIZE: number = 24;

  /**
   * small font size
   */
  static readonly SMALL_FONT_SIZE: number = 14;

  /**
   * vp size
   */
  static readonly VP_SIZE: number = 60;

  /**
   * pixel width
   */
  static readonly PIXEL_WIDTH: number = 200;
}
