/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * animation duration of tab content switching.
   */
  static readonly DURATION_PAGE = 50;

  /**
   * animation duration of tab content switching.
   */
  static readonly DURATION_ADS = 200;

  /**
   * height of head portrait.
   */
  static readonly HEIGHT_HEAD = 40;

  /**
   * height of carousel title.
   */
  static readonly HEIGHT_CAROUSEL_TITLE = 90;

  /**
   * fontSize of description.
   */
  static readonly FONT_SIZE_DESCRIPTION = 12;

  /**
   * font size of photo name.
   */
  static readonly FONT_SIZE_PHOTO_NAME = 14;

  /**
   * font size of sort title.
   */
  static readonly FONT_SIZE_SORT_TITLE = 16;

  /**
   * font size of unchecked title.
   */
  static readonly FONT_SIZE_UNCHECKED = 18;

  /**
   * font size of title.
   */
  static readonly FONT_SIZE_TITLE = 20;

  /**
   * font size of checked title.
   */
  static readonly FONT_SIZE_CHECKED = 24;

  /**
   * font size of tab page which content has only tab name.
   */
  static readonly FONT_SIZE_PAGE_CONTENT = 28;

  /**
   * thinner font.
   */
  static readonly FONT_WEIGHT_LIGHT = 400;

  /**
   * normal font.
   */
  static readonly FONT_WEIGHT_NORMAL = 500;

  /**
   * bold font.
   */
  static readonly FONT_WEIGHT_BOLD = 700;

  /**
   * page layout weight.
   */
  static readonly LAYOUT_WEIGHT = 1;

  /**
   * border angle.
   */
  static readonly BORDER_RADIUS = 12;

  /**
   * line height for more.
   */
  static readonly LINE_HEIGHT_MORE = 19;

  /**
   * line height for navigation.
   */
  static readonly LINE_HEIGHT_NAVIGATION = 28;

  /**
   * space of topBar.
   */
  static readonly SPACE_TOP_BAR = 16;

  /**
   * space of navigation.
   */
  static readonly SPACE_NAVIGATION = 8;

  /**
   * border width of head portrait.
   */
  static readonly WIDTH_HEAD_BORDER = 2;

  /**
   * width of head portrait.
   */
  static readonly WIDTH_HEAD = 40;

  /**
   * radius of head portrait.
   */
  static readonly RADIUS_HEAD = 20;

  /**
   * rolling duration.
   */
  static readonly SWIPER_TIME = 1500;

  /**
   * margin of play page.
   */
  static readonly MARGIN_PLAY_PAGE = 10;

  /**
   * margin of text bottom.
   */
  static readonly BOTTOM_TEXT = 4;

  /**
   * margin of banner top.
   */
  static readonly TOP_ADS = 12;

  /**
   * margin of navigation left.
   */
  static readonly LEFT_POSITION = '3%';

  /**
   * margin of banner left.
   */
  static readonly ADS_LEFT = 12;

  /**
   * top margin of picture name.
   */
  static readonly TOP_NAME = 8;

  /**
   * top margin of picture description.
   */
  static readonly TOP_DESCRIPTION = 4;

  /**
   * top margin of vote icon.
   */
  static readonly TOP_IMAGE_VOTE = 20;

  /**
   * top margin of head portrait.
   */
  static readonly TOP_HEAD = 40;

  /**
   * maximum width.
   */
  static readonly FULL_WIDTH = '100%';

  /**
   * maximum height.
   */
  static readonly FULL_HEIGHT = '100%';

  /**
   * width of play model.
   */
  static readonly WIDTH_PLAY = '95%';

  /**
   * width of tab page.
   */
  static readonly PAGE_WIDTH = '94.4%';

  /**
   * width of sort name.
   */
  static readonly WIDTH_SORT_NAME = '62.2%';

  /**
   * sort content width of all.
   */
  static readonly WIDTH_SORT = '92%';

  /**
   * sort content width of movie.
   */
  static readonly WIDTH_MOVIE_SORT = '90%';

  /**
   * width of picture.
   */
  static readonly WIDTH_PICTURE = '72%';

  /**
   * height of banner.
   */
  static readonly HEIGHT_BANNER = '27%';

  /**
   * width of vote icon.
   */
  static readonly WIDTH_VOTE = '8.9%';

  /**
   * width of back icon.
   */
  static readonly WIDTH_BACK_ICON = '6.7%';

  /**
   * top margin of sort.
   */
  static readonly MARGIN_TOP_SORT = '3.2%';

  /**
   * bottom margin of sort.
   */
  static readonly MARGIN_BOTTOM_SORT = '1.7%';

  /**
   * bottom margin of grid.
   */
  static readonly MARGIN_BOTTOM_GRID = '4.2%';

  /**
   * height of video.
   */
  static readonly WIDTH_VIDEO = '26.2%';

  /**
   * number of columns.
   */
  static readonly TWO_COLUMNS = '1fr 1fr';

  /**
   * number of rows.
   */
  static readonly TWO_ROWS = '1fr 1fr';

  /**
   * number of columns.
   */
  static readonly THREE_COLUMNS = '1fr 1fr 1fr';

  /**
   * number of rows.
   */
  static readonly THREE_ROWS = '1fr 1fr 1fr';

  /**
   * gap of columns.
   */
  static readonly GAP_COLUMNS = '2.2%';

  /**
   * height of grid.
   */
  static readonly HEIGHT_GRID = '45%';

  /**
   * height of movie description.
   */
  static readonly HEIGHT_DESCRIPTION = '12.3%';

  /**
   * height of top bar.
   */
  static readonly TOP_BAR_HEIGHT = '7.2%';

  /**
   * height of comment icon.
   */
  static readonly HEIGHT_COMMENT = '4.1%';

  /**
   * height of back icon.
   */
  static readonly HEIGHT_BACK_ICON = '3.1%';

  /**
   * horizontal position of comment.
   */
  static readonly OFFSET_COMMENT_X = '-5%';

  /**
   * vertical position of comment.
   */
  static readonly OFFSET_COMMENT_Y = '10%';

  /**
   * vertical position of description.
   */
  static readonly OFFSET_DESCRIPTION_Y = '45%';

  /**
   * start position.
   */
  static readonly START_POSITION = '0%';

  /**
   * video play page.
   */
  static readonly PLAY_PAGE = 'pages/PageVideo';

  /**
   * home page.
   */
  static readonly HOME_PAGE = 'pages/SwiperIndex';
}