/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const WEB_PAGE_URI: string = 'pages/WebPage';

export const LOCAL_PATH: Resource = $rawfile('index.html');

/**
 * The host address of the server.
 */
export const CLOUD_PATH: string = 'http://xxx.xxx.xxx.xxx:9588/index.html';

export const WEB_ALERT_DIALOG_TEXT_VALUE: string = '恭喜您抽中:';

export const WebConstant = {
  FULL_WIDTH: '100%',
  FULL_HEIGHT: '100%',
  WIDTH: '93.3%',
  HEIGHT: '55.9%',
  MARGIN_TOP: '7.1%',
  MARGIN_LEFT: '3.3%',
  MARGIN_RIGHT: '3.3%',
  TOP_ROW_HEIGHT: '7.2%',
  IMAGE_WIDTH: '5.6%',
  IMAGE_HEIGHT: '32%',
  IMAGE_MARGIN_LEFT: '7.2%',
  TEXT_VALUE_WIDTH: '35.6%',
  TEXT_VALUE_HEIGHT: '3.1%',
  TEXT_VALUE_MARGIN_TOP: '3.1%',
  TEXT_VALUE_FONT_SIZE: 18,
  TEXT_VALUE_FONT_WEIGHT: 500,
  TIP_TEXT_VALUE_WIDTH: '15.6%',
  TIP_TEXT_VALUE_HEIGHT: '2.4%',
  TIP_TEXT_VALUE_FONT_SIZE: 14,
  TIP_TEXT_VALUE_MARGIN_TOP: '0.9%',
  TIP_TEXT_VALUE_OPACITY: 0.6,
  TOP_TEXT_WIDTH: '82.2%',
  TOP_TEXT_HEIGHT: '50%',
  TOP_TEXT_MARGIN_LEFT: '5%',
  TOP_TEXT_FONT_SIZE: 20,
  BUTTON_WIDTH: '86.7%',
  BUTTON_HEIGHT: '5.1%',
  BUTTON_MARGIN_TOP: '10%',
  BUTTON_BORDER_RADIUS: '20',
  BUTTON_FONT_SIZE: 16,
  DURATION: 3000,
  PROGRESS_MIN: 0,
  PROGRESS_MAX: 100,
  PROGRESS_STEP: 10,
  MILLI_SECONDS: 100,
  PROGRESS_STROKE_WIDTH: 15,
  PROGRESS_SCALE_COUNT: 15,
  PROGRESS_SCALE_WIDTH: 5,
  PROGRESS_WIDTH: 80,
  PROGRESS_POSITION_X: '40%',
  PROGRESS_POSITION_Y: '30%'
}

export const MainConstant = {
  FULL_HEIGHT: '100%',
  IMAGE_HEIGHT: '38.7%',
  BUTTON_MARGIN_TOP_BUTTON: '3.1%',
  BUTTON_HEIGHT: '5.1%',
  BUTTON_MARGIN_TOP: '4.6%',
  BUTTON_WIDTH: '86.7%',
  BUTTON_BORDER_RADIUS: 20,
  BUTTON_FONT_SIZE: 16
}
