/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class ControlConstants {
  /**
   * Play control value.
   */
  static readonly PLAY: string = 'play';

  /**
   * Pause control value.
   */
  static readonly PAUSE: string = 'pause';

  /**
   * Play next control value.
   */
  static readonly NEXT: string = 'next';

  /**
   * Play previous control value.
   */
  static readonly PREVIOUS: string = 'previous';

  /**
   * review value.
   */
  static readonly REVIEW: string = 'review';

  /**
   * Play mode control value.
   */
  static readonly PLAY_MODE: string = 'playMode';

  /**
   * Play list control value.
   */
  static readonly PLAY_LIST: string = 'playList';
}