/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Constants for player area.
 */
export class PlayerConstants {
  /**
   * The font size of the singer is smaller.
   */
  static readonly FONT_REDUCE: number = 4;

  /**
   * The layout weight of player control.
   */
  static readonly LAYOUT_WEIGHT_PLAYER_CONTROL: number = 1;

  /**
   * The display priority is 1.
   */
  static readonly DISPLAY_PRIORITY_ONE: number = 1;

  /**
   * The display priority is 2.
   */
  static readonly DISPLAY_PRIORITY_TWO: number = 2;

  /**
   * The display priority is 3.
   */
  static readonly DISPLAY_PRIORITY_THREE: number = 3;

  /**
   * The rotate is 360.
   */
  static readonly ROTATE: number = 360;

  /**
   * The animation duration is 3000.
   */
  static readonly ANIMATION_DURATION: number = 3000;

  /**
   * The value of iterations.
   */
  static readonly ITERATIONS: number = -1;
}