/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Constants for common components.
 */
export class SongConstants {
  /**
   * Song list index add 1.
   */
  static readonly ADD_INDEX_ONE: number = 1;

  /**
   * Song list index add 2.
   */
  static readonly ADD_INDEX_TWO: number = 2;

  /**
   * Song list index add 3.
   */
  static readonly ADD_INDEX_THREE: number = 3;

  /**
   * The slice start is 0.
   */
  static readonly SLICE_START_ZERO: number = 0;

  /**
   * The slice end is 3.
   */
  static readonly SLICE_END_THREE: number = 3;

  /**
   * The slice index is 1.
   */
  static readonly SLICE_INDEX_ONE: number = 1;

  /**
   * The slice index is 2.
   */
  static readonly SLICE_INDEX_TWO: number = 2;

  /**
   * The slice index is 4.
   */
  static readonly SLICE_INDEX_FOUR: number = 4;

  /**
   * The form id is no exit.
   */
  static readonly ID_NO_EXIT: number = 16501001;

  /**
   * The duration of page transition.
   */
  static readonly TRANSITION_DURATION: number = 500;
}