/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * database preference id.
 */
export const PREFERENCE_ID = 'storageId';

/**
 * database alarm data key.
 */
export const ALARM_KEY = 'alarmData';

/**
 * database alarm item key.
 */
export const PARAM_KEY = 'alarmItem';

export const CommonConstants = {
  /**
   * common full length
   */
  FULL_LENGTH: '100%',

  /**
   * default string space.
   */
  DEFAULT_STRING_SPACE: ' ',

  /**
   * default string comma.
   */
  DEFAULT_STRING_COMMA: '，',

  /**
   * default string no repeat.
   */
  DEFAULT_STRING_NO_REPEAT: '不重复',

  /**
   * default number negative.
   */
  DEFAULT_NUMBER_NEGATIVE: -1,

  /**
   * default layout weight.
   */
  DEFAULT_LAYOUT_WEIGHT: 1,

  /**
   * default number monday.
   */
  DEFAULT_NUMBER_MONDAY: 1,

  /**
   * default number tuesday.
   */
  DEFAULT_NUMBER_TUESDAY: 2,

  /**
   * default number wednesday.
   */
  DEFAULT_NUMBER_WEDNESDAY: 3,

  /**
   * default number thursday.
   */
  DEFAULT_NUMBER_THURSDAY: 4,

  /**
   * default number friday.
   */
  DEFAULT_NUMBER_FRIDAY: 5,

  /**
   * default number saturday.
   */
  DEFAULT_NUMBER_SATURDAY: 6,

  /**
   * default number sunday.
   */
  DEFAULT_NUMBER_SUNDAY: 7,

  /**
   * default single.
   */
  DEFAULT_SINGLE: 1,

  /**
  * default double.
  */
  DEFAULT_DOUBLE: 2,

  /**
   * default data picker hour selection.
   */
  DEFAULT_DATA_PICKER_HOUR_SELECTION: 2,

  /**
   * default total minute.
   */
  DEFAULT_TOTAL_MINUTE: 60,

  /**
   * default string monday.
   */
  DEFAULT_STRING_MONDAY: '周一',

  /**
   * default string tuesday.
   */
  DEFAULT_STRING_TUESDAY: '周二',

  /**
   * default string wednesday.
   */
  DEFAULT_STRING_WEDNESDAY: '周三',

  /**
   * default string thursday.
   */
  DEFAULT_STRING_THURSDAY: '周四',

  /**
   * default string friday.
   */
  DEFAULT_STRING_FRIDAY: '周五',

  /**
   * default string saturday.
   */
  DEFAULT_STRING_SATURDAY: '周六',

  /**
   * default string sunday.
   */
  DEFAULT_STRING_SUNDAY: '周日',

  /**
   * default number moment.
   */
  DEFAULT_NUMBER_MOMENT: 3,

  /**
   * default interval step.
   */
  DEFAULT_INTERVAL_STEP: 5,

  /**
   * default common degree
   */
  DEFAULT_COMMON_DEGREE: 6,

  /**
   * default pointer width.
   */
  DEFAULT_POINTER_WIDTH: 10,

  /**
   * default total hour.
   */
  DEFAULT_TOTAL_HOUR: 12,

  /**
   * default interval time max.
   */
  DEFAULT_INTERVAL_TIME_MAX: 10,

  /**
   * default interval minute max.
   */
  DEFAULT_INTERVAL_MINUTE_MAX: 30,
}