/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Detail page constant description.
 */
export const DetailConstant = {
  /**
   * detail page day data.
   */
  DAY_DATA: [
    { timeType: 0, delSelect: 0, data: ['上午', '下午'] },
    { timeType: 1, delSelect: 0, data: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'] },
    { timeType: 2, delSelect: 0, data: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12',
    '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
    '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
    '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48',
    '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '00',
    ] }
  ],

  /**
   * week day data.
   */
  WEEKDAY_DATA: [1, 2, 3, 4, 5, 6, 7],

  /**
   * ring duration list data.
   */
  RING_DURATION: [1, 5, 10, 15, 20, 30],

  /**
   * default string minute.
   */
  DEFAULT_STRING_MINUTE: '分钟',

  /**
   * default string group name.
   */
  DEFAULT_STRING_GROUP_NAME: 'radioGroup',

  /**
   * default string provider key.
   */
  DEFAULT_PROVIDER_KEY: 'alarmItemProvide',

  /**
   * default string repeat.
   */
  DEFAULT_STRING_REPEAT: '重复',

  /**
   * default string alarm name.
   */
  DEFAULT_STRING_ALARM_NAME: '闹钟名',

  /**
   * default string interval.
   */
  DEFAULT_STRING_INTERVAL: '再响间隔',

  /**
   * default string duration.
   */
  DEFAULT_STRING_DURATION: '闹铃时长',

  /**
   * default string times.
   */
  DEFAULT_STRING_TIMES: '次',
}