/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * The font weight of application.
 */
enum AppFontWeight {
  BOLD = '400',
  BOLDER = '500',
};

/**
 * The font size of application.
 */
enum AppFontSize {
  SMALLER = 13,
  SMALL = 14,
  MIDDLE = 16,
  LARGE = 20,
  LARGER = 35,
};

export { AppFontSize, AppFontWeight };

/**
 * The percentage of 100.
 */
export const PERCENTAGE_100 = '100%';

/**
 * The percentage of 20.
 */
export const PERCENTAGE_20 = '20%';

/**
 * The percentage of 50.
 */
export const PERCENTAGE_50 = '50%';

/**
 * The text margin of 18.
 */
export const Text_Margin = 18;

/**
 * The style of CardComponent.
 */
export const CardStyle = {
  /**
   * The horizontal margin of CardComponent.
   */
  CARD_MARGIN_HORIZONTAL: 16,

  /**
   * The top margin of CardComponent.
   */
  CARD_MARGIN_TOP: 24,

  /**
   * The vertical padding of CardComponent.
   */
  CARD_PADDING_VERTICAL: 25,

  /**
   * The horizontal padding of CardComponent.
   */
  CARD_PADDING_HORIZONTAL: 16,

  /**
   * The border radius of CardComponent.
   */
  CARD_RADIUS: 18,
};

/**
 * The style of BalanceComponent.
 */
export const BalanceStyle = {
  /**
   * The layout weight of BalanceComponent.
   */
  LAYOUT_WEIGHT: 1,
};

/**
 * The style of ToolBarComponent.
 */
export const ToolBarStyle = {
  /**
   * The bottom margin.
   */
  MARGIN_BOTTOM: 10,

  /**
   * The size of image.
   */
  IMAGE_SIZE: 24,

  /**
   * The weight of layout.
   */
  LAYOUT_WEIGHT: '25%',

  /**
   * The height of divider.
   */
  DIVIDER_HEIGHT: 0.5,

  /**
   * The opacity of divider.
   */
  DIVIDER_OPACITY: 0.05
};

/**
 * The style of NavPage.
 */
export const NavPageStyle = {
  /**
   * The height of Tabs.
   */
  BAR_HEIGHT: 0,

  /**
   * The default position of Tabs.
   */
  POSITION_INITIAL: 0,
};

/**
 * The style of HomePage.
 */
export const HomePageStyle = {
  /**
   * The vertical padding.
   */
  PADDING_VERTICAL: 8,

  /**
   * The horizontal padding.
   */
  PADDING_HORIZONTAL: 16,

  /**
   * The height of blank.
   */
  BLANK_HEIGHT: 15,
};

/**
 * The style of DetailsPage.
 */
export const DetailsPageStyle = {
  /**
   * The size of top image.
   */
  TOP_IMAGE_SIZE: 32,

  /**
   * The margin of top.
   */
  MARGIN_TOP_LAYOUT: 16,

  /**
   * The top margin of title.
   */
  TITLE_MARGIN_TOP: 4,

  /**
   * The bottom margin of title.
   */
  TITLE_MARGIN_BOTTOM: 20,

  /**
   * The height of divider.
   */
  DIVIDER_HEIGHT: 0.25,

  /**
   * The left margin of divider.
   */
  DIVIDER_MARGIN_LEFT: '12%',

  /**
   * The top margin of divider.
   */
  DIVIDER_MARGIN_TOP: 10,

  /**
   * The bottom margin of divider.
   */
  DIVIDER_MARGIN_BOTTOM: 18,

  /**
   * The top margin of comment list.
   */
  COMMENT_LIST_MARGIN_TOP: 10,

  /**
   * The height of top layout.
   */
  TOP_LAYOUT_HEIGHT: '45%',

  /**
   * The height of scroll layout.
   */
  SCROLL_LAYOUT_WEIGHT: '93%',

  /**
   * The weight of tool bar layout.
   */
  TOOLBAR_WEIGHT: '7%',

  /**
   * The image size for more action.
   */
  IMAGE_SIZE_MORE: 14
};

/**
 * ability name.
 */
export const DETAILS_ABILITY_NAME = 'DetailsAbility'















