/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * The constant of BannerComponent.
 */
export const Banner = {
  /**
   * The size of indicator.
   */
  INDICATOR_SIZE: 12,

  /**
   * The width of banner.
   */
  WIDTH: '93%',

  /**
   * The space of column.
   */
  SPACE: 5,

  /**
   * The cache count of Swiper.
   */
  CACHE_COUNT: 2,

  /**
   * The default index of Swiper.
   */
  POSITION: 1,

  /**
   * The interval time of Swiper.
   */
  TIME: 4000,

  /**
   * The duration of Swiper.
   */
  DURATION: 1000,

  /**
   * The item space of Swiper.
   */
  ITEM_SPACE: 0
};

/**
 * The constant of GoodsComponent.
 */
export const GoodsList = {
  /**
   * The padding of grid.
   */
  GRID_PADDING: 12,

  /**
   * The columnsGap of grid.
   */
  SPACE: 8,


  /**
   * The layout direction of grid.
   */
  HORIZONTAL: 0,

  /**
   * The columns template of grid.
   */
  GRID_STYLE: '1fr 1fr',
};

/**
 * The constant of GoodsItemComponent.
 */
export const GoodsListItem = {
  /**
   * The container height of goods name.
   */
  CONTAINER_GOODS_NAME_HEIGHT: 40,

  /**
   * The max line of goods name.
   */
  MAX_LINE_GOODS_NAME: 2,

  /**
   * The margin of goods discounts.
   */
  MARGIN_DISCOUNTS: 5,

  /**
   * The size of goods image.
   */
  GOODS_IMAGE_SIZE: 130,

  /**
   * The top margin of goods image.
   */
  GOODS_IMAGE_MARGIN_TOP: 10,

  /**
   * The border radius of goods label.
   */
  BORDER_RADIUS_LABEL: 5,

  /**
   * The verical padding of goods label.
   */
  PADDING_LABEL_VERTICAL: 8,

  /**
   * The horizontal padding of goods label.
   */
  PADDING_LABEL_HORIZONTAL: 2,

  /**
   * The top margin of goods label container.
   */
  CONTAINER_LABEL_MARGIN_TOP: 6,

  /**
   * The bottom margin of goods label container.
   */
  CONTAINER_LABEL_MARGIN_BOTTOM: 12,

  /**
   * The top margin of text container.
   */
  TEXT_LAYER_MARGIN_TOP: 20,

  /**
   * The width of text container.
   */
  TEXT_LAYER_WIDTH: "98%",

  /**
   * The horizontal padding of item.
   */
  ITEM_PADDING_HORIZONTAL: 10,

  /**
   * The width of border.
   */
  BORDER_WIDTH: 1,

  /**
   * The value of border radius.
   */
  BORDER_RADIUS: 10,
};

/**
 * The constant of TabsComponent.
 */
export const GoodsTabs = {
  /**
   * The height of GoodsTabs.
   */
  BAR_HEIGHT: 50,

  /**
   * The default index of GoodsTabs.
   */
  TABVIEW_POSITION_INDEX_PAGE: 0,

  /**
   * The width of image.
   */
  IMAGE_SIZE_WIDTH: 12,

  /**
   * The height of image.
   */
  IMAGE_SIZE_HEIGHT: 16,


  /**
   * The width of tab.
   */
  TAB_WIDTH: '90%',

  /**
   * The animation duration of Tabs.
   */
  TIME: 400,

  /**
   * The blank width of Tabs setting.
   */
  SETTING_BLANK_WIDTH: 4,

  /**
   * The layout weight of Tabs setting.
   */
  SETTING_LAYOUT: '10%',

  /**
   * The padding of right.
   */
  PADDING_RIGHT: '9%',
};

/**
 * The constant of MenusComponent.
 */
export const Menus = {
  /**
   * The vertical padding of container.
   */
  CONTAINER_PADDING_VERTICAL: 12,

  /**
   * The vertical padding of item.
   */
  ITEM_PADDING_VERTICAL: 16,

  /**
   * The weight of layout.
   */
  LAYOUT_WEIGHT: '25%',
};

/**
 * The constant of SearchComponent.
 */
export const SearchBar = {
  /**
   * The width of layout.
   */
  WEIGHT: '90%',

  /**
   * The size of image.
   */
  IMAGE_SIZE: 20,

  /**
   * The height of SearchBar.
   */
  BAR_HEIGHT: 40,

  /**
   * The right margin of input.
   */
  TEXT_INPUT_MARGIN_RIGHT: 20,

  /**
   * The left padding of container.
   */
  CONTAINER_PADDING_LEFT: 10,

  /**
   * The border radius.
   */
  BORDER_RADIUS: 36,
};

/**
 * The constant of TopBarComponent.
 */
export const TopBar = {
  /**
   * The size of image.
   */
  IMAGE_SIZE: 30,

  /**
   * The height of BalanceComponent.
   */
  HEIGHT: '4%',
};












