/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommodityConstants{
  /**
   * Index of home tab.
   */
  static readonly INDEX_HOME: number = 0;

  /**
   * Index of shopCart tab.
   */
  static readonly INDEX_SHOPPING_CART: number = 2;

  /**
   * The stars of rating.
   */
  static readonly RATING_STARS: number = 5

  /**
   * Text max line value: 2
   */
  static readonly MAX_LINE: number = 2;

  /**
   * String of choose.
   */
  static readonly SPECIAL_CHOOSE: string = '已选';

  /**
   * ConfirmOrderPage url.
   */
  static readonly CONFIRM_ORDER_PAGE_URL: string = 'pages/ConfirmOrderPage';
}