/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class CommonConstants{
  /**
   * The text high
   */
  static TEXT_HEIGHT: number = 50;

  /**
   * The text width
   */
  static DEFAULT_MARGIN: number = 30;

  /**
   * Full the width.
   */
  static FULL_WIDTH: string = '100%';

  /**
   * Full the height.
   */
  static FULL_HEIGHT: string = '100%';

  /**
   * Default fontSize
   */
  static DEFAULT_FONT_SIZE: number = 30;

  /*
   * Log Domain
   * */
  static DOMAIN: number = 0x0000;
}
