/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default  class ErrorCode {
  /**
   * Preference is not initialized.
   */
  static readonly ERROR_PREFERENCE_NOT_INITIALIZED = 15500011;

  /**
   * The network seems to have deserted.
   */
  static readonly ERROR_NETWORK_CONNECT_FAILED = 2100002;
}