/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Constants for Grid components.
 */
export class GridConstants {
  /**
   * Current component width: 4 grids.
   */
  static readonly COLUMN_FOUR: number = 4;

  /**
   * Current component width: 8 grids.
   */
  static readonly COLUMN_EIGHT: number = 8;

  /**
   * Current component width: 12 grids.
   */
  static readonly COLUMN_TWELVE: number = 12;

  /**
   * Current component width: 1 grids.
   */
  static readonly SPAN_ONE: number = 1;

  /**
   * Current component width: 2 grids.
   */
  static readonly SPAN_TWO: number = 2;

  /**
   * Current component width: 3 grids.
   */
  static readonly SPAN_THREE: number = 3;

  /**
   * Current component width: 4 grids.
   */
  static readonly SPAN_FOUR: number = 4;

  /**
   * Current component width: 8 grids.
   */
  static readonly SPAN_EIGHT: number = 8;

  /**
   * Current component width: 12 grids.
   */
  static readonly SPAN_TWELVE: number = 12;

  /**
   * Current component offset 2 grids.
   */
  static readonly OFFSET_TWO: number = 2;

  /**
   * Current component offset 3 grids.
   */
  static readonly OFFSET_THREE: number = 3;

  /**
   * Current component offset 6 grids.
   */
  static readonly OFFSET_SIX: number = 6;

  /**
   * Current component offset 8 grids.
   */
  static readonly OFFSET_EIGHT: number = 8;

  /**
   * Current component gutter 12.
   */
  static readonly GUTTER_TWELVE: number = 12;
}