/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Style constants for all features.
 */
export default class StyleConstants {
  /**
   * Common left the percentage of the 6.7.
   */
  static readonly COMMON_MARGIN_LEFT: string = '6.7%';
  /**
   * Details common margin size the percentage of the 1.5.
   */
  static readonly DETAILS_COMMON_MARGIN: string = '1.5%';
  /**
   * Column details width the percentage of the 93.4.
   */
  static readonly COLUMN_DETAILS_WIDTH: string = '93.4%';
  /**
   * Starring text width the percentage of the 76.6.
   */
  static readonly STARRING_TEXT_WIDTH: string = '76.6%';
  /**
   * Common margin top the percentage of the 3.2.
   */
  static readonly COMMON_MARGIN_TOP: string = '3.2%';
  /**
   * Common margin right the percentage of the 3.3.
   */
  static readonly COMMON_MARGIN_RIGHT: string = '3.3%';
  /**
   * Common margin bottom the percentage of the 1.
   */
  static readonly COMMON_MARGIN_BOTTOM: string = '1%';
  /**
   * Starring width the percentage of the 90.
   */
  static readonly STARRING_WIDTH: string = '90%';
  /**
   * Starring space of the 8.
   */
  static readonly STARRING_SPACE: number = 8;
  /**
   * Rstarring list width the percentage of the 93.3.
   */
  static readonly STARRING_LIST_WIDTH: string = '93.3%';
  /**
   * Rstarring list height the percentage of the 14.4.
   */
  static readonly STARRING_LIST_HEIGHT: string = '14.4%';
  /**
   * Stills text width the percentage of the 76.6.
   */
  static readonly STILLS_TEXT_WIDTH: string = '76.6%';
  /**
   * Stills width the percentage of the 90.
   */
  static readonly STILLS_WIDTH: string = '90%';
  /**
   * Stills list space of the 4.
   */
  static readonly STILLS_LIST_SPACE: number = 4;
  /**
   * Stills list width the percentage of the 93.3.
   */
  static readonly STILLS_LIST_WIDTH: string = '93.3%';
  /**
   * List title margin the percentage of the 1.5.
   */
  static readonly LIST_TITLE_MARGIN: string = '1.5%';
  /**
   * List compoent space of the 12.
   */
  static readonly LIST_COMPONENT_SPACE: number = 12;
  /**
   * Item width the percentage of the 93.4.
   */
  static readonly ITEM_WIDTH: string = '93.4%';
  /**
   * Stars list space of the 3.
   */
  static readonly STARS_LIST_SPACE: number = 3;
  /**
   * Layout weight size of the 1.
   */
  static readonly WEIGHT_ONE: number = 1;
  /**
   * Width the percentage of the 100.
   */
  static readonly FULL_WIDTH: string = '100%';
  /**
   * Height the percentage of the 100.
   */
  static readonly FULL_HEIGHT: string = '100%';
}