/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class CommonConstants {
  static readonly FULL_SIZE = '100%';
  static readonly BOTTOM_IMAGE_SIZE = '40%';
  static readonly BOTTOM_TAB_WIDTH = '25%';
  static readonly BOTTOM_TAB_HEIGHT = '10%';
  static readonly TOP_TAB_HEIGHT = '8%';
  static readonly TOP_FONT_MARGIN = '5%';
  static readonly SWIPER_HEIGHT = '30%';
  static readonly SWIPER_MARGIN = '4%';

  static readonly TOP_FONT_OPACITY = 0.6;
  static readonly SWIPER_FONT_OPACITY = 0.9;
  static readonly LAYOUT_WEIGHT = 1;
  static readonly SWIPER_COUNT_1 = 1;
  static readonly SWIPER_COUNT_2 = 2;
  static readonly SWIPER_COUNT_3 = 3;
  static readonly BORDER_RADIUS = 10;
  static readonly SWIPER_WIDTH = 330;
  static readonly SWIPER_SCALE = 0.9;
  static readonly ITEM_SPACE = 15;
  static readonly PADDING = 15;
  static readonly PADDING_SCALE = 0.05;
}