/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { SwiperItem } from '../common/bean/Item';

export const SwiperList: Array<SwiperItem> = [
  {
    title: $r('app.string.swiper_item_1'),
    img: $r('app.media.Mountain'),
    text: $r('app.string.swiper_text_1')
  },
  {
    title: $r('app.string.swiper_item_2'),
    img: $r('app.media.Street'),
    text: $r('app.string.swiper_text_2')
  },
  {
    title: $r('app.string.swiper_item_3'),
    img: $r('app.media.Bridge'),
    text: $r('app.string.swiper_text_3')
  },
  {
    title: $r('app.string.swiper_item_4'),
    img: $r('app.media.Dandelion'),
    text: $r('app.string.swiper_text_4')
  },
  {
    title: $r('app.string.swiper_item_5'),
    img: $r('app.media.Ferris_wheel'),
    text: $r('app.string.swiper_text_5')
  }
]


