/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ChildListItem } from '../common/bean/Item';

export const List1: ChildListItem = {
  title: $r('app.string.list1_title'),
  Item: [
    {
      title: $r('app.string.list1_1_item'),
      img: $r('app.media.1_1'),
      text: $r('app.string.list1_1_text')
    },
    {
      title: $r('app.string.list1_2_item'),
      img: $r('app.media.1_2'),
      text: $r('app.string.list1_2_text')
    },
    {
      title: $r('app.string.list1_3_item'),
      img: $r('app.media.1_3'),
      text: $r('app.string.list1_3_text')
    },
    {
      title: $r('app.string.list1_4_item'),
      img: $r('app.media.1_4'),
      text: $r('app.string.list1_4_text')
    },
    {
      title: $r('app.string.list1_5_item'),
      img: $r('app.media.1_5'),
      text: $r('app.string.list1_5_text')
    },
    {
      title: $r('app.string.list1_6_item'),
      img: $r('app.media.1_6'),
      text: $r('app.string.list1_6_text')
    },
    {
      title: $r('app.string.list1_7_item'),
      img: $r('app.media.1_7'),
      text: $r('app.string.list1_7_text')
    }
  ]
}

export const List2: ChildListItem = {
  title: $r('app.string.list2_title'),
  Item: [
    {
      title: $r('app.string.list2_1_item'),
      img: $r('app.media.2_1'),
      text: $r('app.string.list2_1_text')
    },
    {
      title: $r('app.string.list2_2_item'),
      img: $r('app.media.2_2'),
      text: $r('app.string.list2_2_text')
    },
    {
      title: $r('app.string.list2_3_item'),
      img: $r('app.media.2_3'),
      text: $r('app.string.list2_3_text')
    },
    {
      title: $r('app.string.list2_4_item'),
      img: $r('app.media.2_4'),
      text: $r('app.string.list2_4_text')
    },
    {
      title: $r('app.string.list2_5_item'),
      img: $r('app.media.2_5'),
      text: $r('app.string.list2_5_text')
    },
    {
      title: $r('app.string.list2_6_item'),
      img: $r('app.media.2_6'),
      text: $r('app.string.list2_6_text')
    },
    {
      title: $r('app.string.list2_7_item'),
      img: $r('app.media.2_7'),
      text: $r('app.string.list2_7_text')
    }
  ]
}

export const List3: ChildListItem = {
  title: $r('app.string.list3_title'),
  Item: [
    {
      title: $r('app.string.list3_1_item'),
      img: $r('app.media.3_1'),
      text: $r('app.string.list3_1_text')
    },
    {
      title: $r('app.string.list3_2_item'),
      img: $r('app.media.3_2'),
      text: $r('app.string.list3_2_text')
    },
    {
      title: $r('app.string.list3_3_item'),
      img: $r('app.media.3_3'),
      text: $r('app.string.list3_3_text')
    },
    {
      title: $r('app.string.list3_4_item'),
      img: $r('app.media.3_4'),
      text: $r('app.string.list3_4_text')
    },
    {
      title: $r('app.string.list3_5_item'),
      img: $r('app.media.3_5'),
      text: $r('app.string.list3_5_text')
    },
    {
      title: $r('app.string.list3_6_item'),
      img: $r('app.media.3_6'),
      text: $r('app.string.list3_6_text')
    },
    {
      title: $r('app.string.list3_7_item'),
      img: $r('app.media.3_7'),
      text: $r('app.string.list3_7_text')
    }
  ]
}

export const ListResource: Array<ChildListItem> = [
  List1,
  List2,
  List3
]