/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * the Mock file instead of network data.
 */
export { rankData1, rankData2 }

const rankData1: object[] = [
  {
    'id': '1',
    'name': $r('app.string.fruit_apple'),
    'vote': '12080',
  },
  {
    'id': '2',
    'name': $r('app.string.fruit_grapes'),
    'vote': '10320',
  },
  { 'id': '3',
    'name': $r('app.string.fruit_watermelon'),
    'vote': '9801',
  },
  {
    'id': '4',
    'name': $r('app.string.fruit_banana'),
    'vote': '8431',
  },
  { 'id': '5',
    'name': $r('app.string.fruit_pineapple'),
    'vote': '7546',
  },
  { 'id': '6',
    'name': $r('app.string.fruit_durian'),
    'vote': '7431',
  },
  { 'id': '7',
    'name': $r('app.string.fruit_red_grape'),
    'vote': '7187',
  },
  { 'id': '8',
    'name': $r('app.string.fruit_pears'),
    'vote': '7003',
  },
  { 'id': '9',
    'name': $r('app.string.fruit_carambola'),
    'vote': '6794',
  },
  { 'id': '10',
    'name': $r('app.string.fruit_guava'),
    'vote': '6721',
  },
];

const rankData2: object[] = [
  { 'id': '11',
    'name': $r('app.string.fruit_watermelon'),
    'vote': '8836',
  },
  { 'id': '12',
    'name': $r('app.string.fruit_apple'),
    'vote': '8521',
  },

  { 'id': '13',
    'name': $r('app.string.fruit_banana'),
    'vote': '8431',
  },
  { 'id': '14',
    'name': $r('app.string.fruit_grapes'),
    'vote': '7909',
  },
  { 'id': '15',
    'name': $r('app.string.fruit_red_grape'),
    'vote': '7547',
  },
  { 'id': '16',
    'name': $r('app.string.fruit_pears'),
    'vote': '7433',
  },
  { 'id': '17',
    'name': $r('app.string.fruit_pineapple'),
    'vote': '7186',
  },
  { 'id': '18',
    'name': $r('app.string.fruit_durian'),
    'vote': '7023',
  },
  { 'id': '19',
    'name': $r('app.string.fruit_guava'),
    'vote': '6794',
  },
  { 'id': '20',
    'name': $r('app.string.fruit_carambola'),
    'vote': '6721',
  },
];