/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  /**
   * The space of column component.
   */
  static readonly SPACE_12 = 12;

  /**
   * The font weight of needed component.
   */
  static readonly FONT_WEIGHT_400 = 400;

  /**
   * The opacity of needed component.
   */
  static readonly OPACITY_4 = 0.4;
  static readonly OPACITY_6 = 0.6;

  /**
   * The ratio of component's width and height.
   */
  static readonly ASPECT_RATIO_176 = 1.76;

  /**
   * The percent of component's width and height.
   */
  static readonly CONTAINER_WIDTH = '100%'
  static readonly CONTAINER_HALF_WIDTH = '49%'
  static readonly CONTAINER_HEIGHT = '100%'
  static readonly BAR_WIDTH = '80%'

  /**
   * The logger tag of outer component.
   */
  static readonly OUTER_TAG = 'Outer';

  /**
   * The order number of tab component.
   */
  static readonly FIRST_TAB = 0;
  static readonly SECOND_TAB = 1;

  /**
   * The animate name of the third library.
   */
  static readonly ANIMATE_NAME = 'data';

  /**
   * The zero frame of the third library.
   */
  static readonly ZERO_FRAME = 0;
}



