/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Style constants for all Component.
 */
class StyleConstants {
  /**
   * Font size.
   */
  FONT_SIZE = 20;

  /**
   * Font weight.
   */
  FONT_WEIGHT = 500;

  /**
   * One hundred percent.
   */
  FULL_PERCENT = '100%';

  /**
   * The font size of text component.
   */
  TEXT_FONT_SIZE = 25;

  /**
   * The height of text component.
   */
  TEXT_HEIGHT = '3.2%';

  /**
   * The height of textInput component.
   */
  TEXT_INPUT_HEIGHT = '7%';

  /**
   * The width of textInput component.
   */
  TEXT_INPUT_WIDTH = '93%';

  /**
   * The bottom margin of the text component.
   */
  TEXT_MARGIN_BOTTOM = '2%';

  /**
   * The left margin of the text component.
   */
  TEXT_MARGIN_LEFT = '7%';

  /**
   * Letter spacing.
   */
  LETTER_SPACING = '1.58';

  /**
   * Margin top
   */
  MARGIN_TOP = '8%';

  /**
   * Small margin bottom
   */
  MARGIN_BOTTOM_SMALL = '4%';

  /**
   * Big margin bottom
   */
  MARGIN_BOTTOM_BIG = '390vp';

  /**
   * The height of button component.
   */
  BUTTON_HEIGHT = '6%';

  /**
   * The width of button component.
   */
  BUTTON_WIDTH = '87%';

  /**
   * The bottom margin of the button component.
   */
  BUTTON_MARGIN_BOTTOM = '24vp';
}

export default new StyleConstants();