/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class PlayConstants {
  /**
   * Play control index.
   */
  static readonly PLAY_INDEX: number = 2;

  /**
   * The value of slide step.
   */
  static readonly SLIDE_STEP: number = 1;

  /**
   * The value of gridRow gutter twelve.
   */
  static readonly GRID_COL_GUTTER: number = 12;

  /**
   * The value of gridRow column four.
   */
  static readonly COLUMN_FOUR: number = 4;

  /**
   * The value of gridRow column eight.
   */
  static readonly COLUMN_EIGHT: number = 8;

  /**
   * The value of gridRow column twelve.
   */
  static readonly COLUMN_TWELVE: number = 12;

  /**
   * The value of gridCol span four.
   */
  static readonly SPAN_FOUR: number = 4;

  /**
   * The value of gridCol span six.
   */
  static readonly SPAN_SIX: number = 6;

  /**
   * The value of gridCol span eight.
   */
  static readonly SPAN_EIGHT: number = 8;

  /**
   * The value of gridCol offset one.
   */
  static readonly OFFSET_ONE: number = 1;

  /**
   * The value of gridCol offset two.
   */
  static readonly OFFSET_TWO: number = 2;

  /**
   * The value of gridCol offset three.
   */
  static readonly OFFSET_THREE: number = 3;

  /**
   * The value of gridCol offset six.
   */
  static readonly OFFSET_SIX: number = 6;

  /**
   * The value of five hundred.
   */
  static readonly FIVE_HUNDRED: number = 500;

  /**
   * The value of four hundred.
   */
  static readonly FOUR_HUNDRED: number = 400;

  /**
   * The value of image background blur.
   */
  static readonly BLUR: number = 50;

  /**
   * The background value of eighty percent transparency white.
   */
  static readonly EIGHTY_WHITE: number = 0.5;

  /**
   * The background value of ninety percent transparency white.
   */
  static readonly NINETY_WHITE: number = 1.0;

  /**
   * The color value of eighty percent transparency white.
   */
  static readonly EIGHTY_WHITE_COLOR: string = '#ccffffff';

  /**
   * The color value of ninety percent transparency white.
   */
  static readonly NINETY_WHITE_COLOR: string = '#e6ffffff';

  /**
   * The value of lg.
   */
  static readonly LG: string = 'lg';

  /**
   * The tab text value of song.
   */
  static readonly TAB_SONG: string = '歌曲';

  /**
   * The tab text value of lyrics.
   */
  static readonly TAB_LYRICS: string = '歌词';

  /**
   * The tab text value of lyrics.
   */
  static readonly LYRICS_CONTENT: string = '此歌曲为没有填词的纯音乐，请您欣赏';

  /**
   * The value tab width.
   */
  static readonly TAB_WIDTH: string = '36%';
}