/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Constants for common text and style.
 */
export class CommonConstants {
  /**
   * The full size of container.
   */
  static readonly FULL_SIZE: string = '100%';

  /**
   * Content width.
   */
  static readonly CONTENT_WIDTH: string = '87%';

  /**
   * Content height.
   */
  static readonly CONTENT_HEIGHT: string = '90%';

  /**
   * Common value.
   */
  static readonly COMMON_VALUE: number = 480;
}