/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class HomeConstants {
  /**
   * Top tab topics.
   */
  static readonly TOP_TOPIC_LIST: string[] = ['精选', '视频', '社区', '新闻', '购物', '科技', '财经', '历史', '军事'];

  /**
   * Icon list.
   */
  static readonly ICON_LIST: string[] = ['全部', '周热榜', '免费', '经典', '专区', '儿童专区', '华为专区', '付费精品',
    '健身专区'];

  /**
   * Banner text 1.
   */
  static readonly BANNER_TEXT_1: string = '华为MateBook系列';

  /**
   * Banner text 2.
   */
  static readonly BANNER_TEXT_2: string = '新 品 发 布 会';

  /**
   * Banner text 3.
   */
  static readonly BANNER_TEXT_3: string = '<HDD> | 成都站';

  /**
   * Banner text 4.
   */
  static readonly BANNER_TEXT_4: string = '暨HMS Core 6.0交流会';

  /**
   * Banner text 5.
   */
  static readonly BANNER_TEXT_5: string = '万    象    新    生';

  /**
   * Banner text 6.
   */
  static readonly BANNER_TEXT_6: string = '华为旗舰新品发布会';

  /**
   * Banner text 7.
   */
  static readonly BANNER_TEXT_7: string = 'HUAWEI P60系列';

  /**
   * Banner text 8.
   */
  static readonly BANNER_TEXT_8: string = '华为春季旗舰新品发布会';

  /**
   * Banner text 1 left position for sm.
   */
  static readonly BANNER_TEXT_1_MARGIN_SM: string = '52%';

  /**
   * Banner text 1 left position for md.
   */
  static readonly BANNER_TEXT_1_MARGIN_MD: string = '53%';

  /**
   * Banner text 1 left position for lg.
   */
  static readonly BANNER_TEXT_1_MARGIN_LG: string = '59%';

  /**
   * Banner text 2 left position for sm.
   */
  static readonly BANNER_TEXT_2_MARGIN_SM: string = '56%';

  /**
   * Banner text 2 left position for md.
   */
  static readonly BANNER_TEXT_2_MARGIN_MD: string = '58%';

  /**
   * Banner text 2 left position for lg.
   */
  static readonly BANNER_TEXT_2_MARGIN_LG: string = '63%';

  /**
   * Banner text 3 left position for sm.
   */
  static readonly BANNER_TEXT_3_MARGIN_SM: string = '10%';

  /**
   * Banner text 3 left position for md.
   */
  static readonly BANNER_TEXT_3_MARGIN_MD: string = '7%';

  /**
   * Banner text 3 left position for lg.
   */
  static readonly BANNER_TEXT_3_MARGIN_LG: string = '5%';

  /**
   * Banner text 4 left position for sm.
   */
  static readonly BANNER_TEXT_4_MARGIN_SM: string = '10%';

  /**
   * Banner text 4 left position for md.
   */
  static readonly BANNER_TEXT_4_MARGIN_MD: string = '7%';

  /**
   * Banner text 4 left position for lg.
   */
  static readonly BANNER_TEXT_4_MARGIN_LG: string = '5%';

  /**
   * Video grid rate list.
   */
  static readonly VIDEO_GRID_RATES: string[] = ['7.8', '8.0', '7.9', '8.4', '7.8', '8.0', '7.9', '8.4', '7.6', '8.0'];

  /**
   * Video grid name list.
   */
  static readonly VIDEO_GRID_NAMES: string[] = ['建筑人文史迹', '生命之谜语', '自然地貌一览', '舞动者们', '万家灯火',
    '山河壮丽 下集', '山河壮丽 中集', '山河壮丽 上集', '山河壮丽 上集', '山河壮丽 上集'];

  /**
   * Video grid content list.
   */
  static readonly VIDEO_GRID_CONTENTS: string[] = ['欧洲建筑的历史责任在......', '小小世界的生存智慧......',
    '亿万年前地貌的痕迹是......', '那些艺术者们信仰是那......', '莹莹亮光是被治愈游子......', '桂林山水甲天下,阳朔......',
    '亿万年前地貌的痕迹是......', '这是千百年前的痕迹是......', '这是千百年前的痕迹是......', '这是千百年前的痕迹是......'];

  /**
   * New video grid rate list.
   */
  static readonly NEW_VIDEO_RATES: string[] = ['', '', '7.9', '7.9', '7.9', '7.9', '7.9'];

  /**
   * New video name list.
   */
  static readonly NEW_VIDEO_NAMES: string[] = ['HUAWEI M...', '华为全场景...', '自然地貌一览', '万家灯火', '山河壮丽 中集',
    '山河壮丽 中集', '山河壮丽 中集'];

  /**
   * New video content list.
   */
  static readonly NEW_VIDEO_CONTENTS: string[] = ['全球新品发布...', '华为终端·华...', '亿万年前地貌的...',
    '那是希望的光亮...', '亿万年前地貌的...','亿万年前地貌的...','亿万年前地貌的...'];

  /**
   * Main daily video rate.
   */
  static readonly MAIN_DAILY_VIDEO_RATE: string = '8.4';

  /**
   * Main daily video name.
   */
  static readonly MAIN_DAILY_VIDEO_NAME: string = '万家灯火：那是希望的光亮';

  /**
   * Main daily video content.
   */
  static readonly MAIN_DAILY_VIDEO_CONTENT: string = '那是希望的......';

  /**
   * Main daily video more info.
   */
  static readonly MAIN_DAILY_VIDEO_MORE: string = '万家灯火';

  /**
   * Daily video rate list.
   */
  static readonly DAILY_VIDEO_RATES: string[] = ['7.9', '7.9', '7.9', '7.9'];

  /**
   * Daily video name list.
   */
  static readonly DAILY_VIDEO_NAMES: string[] = ['山河壮丽 下集', '万家灯火', '山河壮丽 上集', '山河壮丽 中集'];

  /**
   * Daily video name list.
   */
  static readonly DAILY_VIDEO_CONTENTS: string[] = ['桂林山水甲天下，阳朔...', '荧荧亮光是被治愈游子...', '欧洲建筑的...',
    '欧洲建筑的...'];

  /**
   * Previous video name list one.
   */
  static readonly PREVIOUS_VIDEO_NAMES_ONE: string[] = ['华为旗舰新品发布会', '华为折叠屏旗舰及全场景新品发布会',
    '2022华为全屋智能及全场景新品春季...'];

  /**
   * Previous video content list one.
   */
  static readonly PREVIOUS_VIDEO_CONTENTS_ONE: string[] = ['发布会 · 华为终端 · 202...', '发布会 · 华为终端 · 202...',
    '华为终端 · 华为资讯 · 20...'];

  /**
   * Previous video more info list one.
   */
  static readonly PREVIOUS_VIDEO_MORE_ONE: string[] = ['75.2万次播放', '9.8万次播放', '10.1万次播放'];

  /**
   * Previous video name list two.
   */
  static readonly PREVIOUS_VIDEO_NAMES_TWO: string[] = ['华为全场景智慧生...', 'HUAWEI Mate 30...', 'HUAWEI Mate 40...',
    '折叠万象', '华为全场景智慧生...', 'nova 10 系列及全...'];

  /**
   * Previous video content list two.
   */
  static readonly PREVIOUS_VIDEO_CONTENTS_TWO: string[] = ['华为终端·华为资讯·...', '全球新品发布会 慕尼...',
    '华为终端·华为资讯·...', '华为冬季旗舰新品发...', '华为终端·华为资讯·...', '华为终端·华为资讯·...'];

  /**
   * XComponent type.
   */
  static readonly X_COMPONENT_TYPE: string = 'surface';

  /**
   * Half percent.
   */
  static readonly HALF_PERCENT: string = '50%';

  /**
   * Banner text letter space list.
   */
  static readonly BANNER_TEXT_LETTER_SPACES: string[] = ['2vp', '3vp', '1vp'];

  /**
   * Swiper item space.
   */
  static readonly SWIPER_ITEM_SPACE: string = '12vp';

  /**
   * Banner row space.
   */
  static readonly BANNER_ROW_SPACE: string = '12vp';

  /**
   * Home sub title list.
   */
  static readonly HOME_SUB_TITLES: string[] = ['新片发布', '每日佳片', '往期回顾'];

  /**
   * New video rows template.
   */
  static readonly NEW_VIDEO_ROWS_TEMPLATE: string = '1fr';

  /**
   * Search top tab bar list space list.
   */
  static readonly SEARCH_TAB_LIST_SPACES: string[] = ['16vp', '24vp', '36vp'];

  /**
   * Main daily video button text.
   */
  static readonly HOME_BUTTON_TEXT: string[] = ['关注', '继续播放', '播放', '缓存'];

  /**
   * Previous two list translate position.
   */
  static readonly PREVIOUS_TWO_TRANSLATE_MD: string = '-42vp';

  /**
   * Search placeholder.
   */
  static readonly SEARCH_PLACEHOLDER: string = '搜索...';

  /**
   * Video dialog option list.
   */
  static readonly VIDEO_DIALOG_OPTIONS: string[] = ['追剧', '收藏', '点赞'];

  /**
   * Side bar icon list height.
   */
  static readonly SIDE_ICON_LIST_HEIGHT: string = '25%';

  /**
   * Square brackets.
   */
  static readonly SQUARE_BRACKETS: string[] = ['[', ']'];

  /**
   * Immersive banner text.
   */
  static readonly IMMERSIVE_BANNER_TEXT: string[] = ['华为 Mate Book 系列', '新品发布会'];

  /**
   * Immersive text letter spacing list.
   */
  static readonly IMMERSIVE_TEXT_LETTER_SPACINGS: string[] = ['1vp', '10vp'];

  /**
   * Immersive text margin left list.
   */
  static readonly IMMERSIVE_TEXT_LEFT_MARGIN: string[] = ['47%', '48%'];

  /**
   * Height unit.
   */
  static readonly HEIGHT_UNIT: string = 'vp';

  /**
   * Dot indicator number.
   */
  static readonly DOT_INDICATOR_NUMBER: number[] = [1, 2, 3, 4, 5];

  /**
   * Two.
   */
  static readonly TWO: number = 2;

  /**
   * Five.
   */
  static readonly FIVE: number = 5;

  /**
   * Six.
   */
  static readonly SIX: number = 6;

  /**
   * Seven.
   */
  static readonly SEVEN: number = 7;

  /**
   * Nine.
   */
  static readonly NINE: number = 9;

  /**
   * Video dialog height list.
   */
  static readonly VIDEO_DIALOG_HEIGHTS: number[] = [161, 268, 347];

  /**
   * Video dialog aspect ratio.
   */
  static readonly VIDEO_DIALOG_ASPECT_RATIO: number = 1.74;

  /**
   * New banner aspect ratio.
   */
  static readonly NEW_BANNER_ASPECT_RATIO: number = 1.5;

  /**
   * Home header background change height.
   */
  static readonly BACKGROUND_CHANGE_HEIGHT: number = 286;

  /**
   * Video grid item space.
   */
  static readonly VIDEO_GRID_ITEM_SPACE: number = 12;

  /**
   * Video grid margin.
   */
  static readonly VIDEO_GRID_MARGIN: number = 48;

  /**
   * Lg sidebar width.
   */
  static readonly LG_SIDEBAR_WIDTH: number = 96;

  /**
   * Video grid description height.
   */
  static readonly VIDEO_GRID_DESCRIPTION_HEIGHT: number = 102;

  /**
   * New video aspect ratio.
   */
  static readonly NEW_VIDEO_ASPECT_RATIO: number = 0.72;

  /**
   * New video description height.
   */
  static readonly NEW_VIDEO_DESCRIPTION_HEIGHT: number = 45;

  /**
   * Daily video description height.
   */
  static readonly DAILY_VIDEO_DESCRIPTION_HEIGHT: number[] = [102, 62];

  /**
   * Previous two ratio list.
   */
  static readonly PREVIOUS_TWO_RATIOS: number[] = [0.76, 0.89, 0.86, 0.74, 0.8, 0.9, 0.83];

  /**
   * Banner aspect ratio list.
   */
  static readonly BANNER_RATIOS: number[] = [1.5, 1.83, 2.33];

  /**
   * Home header height for sm.
   */
  static readonly HOME_HEADER_HEIGHT_SM: number = 112;

  /**
   * Window undefined top.
   */
  static readonly WINDOW_UNDEFINED_TOP: number = 39;

  /**
   * Window undefined left.
   */
  static readonly WINDOW_UNDEFINED_LEFT: number = 5;

  /**
   * Eleven.
   */
  static readonly ELEVEN: number = 11;
}