/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class Constants {
  /**
   * label font weight 400.
   */
  static readonly LABEL_FONT_WEIGHT: number = 400;

  /**
   * title font weight 500.
   */
  static readonly TITLE_FONT_WEIGHT: number = 500;

  /**
   * course item padding 12.
   */
  static readonly COURSE_ITEM_PADDING: number = 12;

  /**
   * loading duration 2000.
   */
  static readonly LOADING_DURATION: number = 2000;

  /**
   * title line number 2.
   */
  static readonly TITLE_LINE_NUMBER: number = 2;

  /**
   * 100 percent.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * classify title percent.
   */
  static readonly CLASSIFY_TITLE_PERCENT: string = '55%';
}
