/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class CommonConstants {

  /**
   * Height and width is 100%.
   * */
  static readonly FULL_PARENT: string = '100%';

  /**
   * Font weight.
   * */
  static readonly FONT_WEIGHT: number = 500;

  /**
   * Max lines.
   */
  static readonly MAX_LINES: number = 1;

  /**
   * TextInput layout weight.
   */
  static readonly TEXTINPUT_LAYOUT_WEIGHT: number = 1;

  /**
   * Bigger than 999999999 using scientific notation.
   */
  static readonly MAX_RESULT: number = 999999999;

  /**
   * Exponential count.
   */
  static readonly EXPONENTIAL_COUNT = 9;

  /**
   * Fixed count.
   */
  static readonly FIXED_COUNT = 2;
}