/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { DriveTabsItem } from '@ohos/common';

export const DriveList: Array<DriveTabsItem> = [
  {
    img: $r('app.media.ic_drive_1'),
    title: $r('app.string.recently_play1_title'),
    intro: $r('app.string.recently_play1_intro')
  },
  {
    img: $r('app.media.ic_drive_2'),
    title: $r('app.string.recently_play2_title'),
    intro: $r('app.string.recently_play2_intro')
  },
  {
    img: $r('app.media.ic_drive_3'),
    title: $r('app.string.recently_play3_title'),
    intro: $r('app.string.recently_play3_intro')
  },
  {
    img: $r('app.media.ic_drive_4'),
    title: $r('app.string.recently_play4_title'),
    intro: $r('app.string.recently_play4_intro')
  },
  {
    img: $r('app.media.ic_drive_5'),
    title: $r('app.string.recently_play5_title'),
    intro: $r('app.string.recently_play5_intro')
  },
  {
    img: $r('app.media.ic_drive_6'),
    title: $r('app.string.recently_play6_title'),
    intro: $r('app.string.recently_play6_intro')
  },
  {
    img: $r('app.media.ic_drive_7'),
    title: $r('app.string.recently_play7_title'),
    intro: $r('app.string.recently_play7_intro')
  }
]