/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * The constant of BannerComponent.
 */
export class Banner {
  /**
   * The size of indicator.
   */
  static readonly INDICATOR_SIZE: number = 12;

  /**
   * The width of banner.
   */
  static readonly WIDTH: string = '93%';

  /**
   * The space of column.
   */
  static readonly SPACE: number = 5;

  /**
   * The cache count of Swiper.
   */
  static readonly CACHE_COUNT: number = 2;

  /**
   * The default index of Swiper.
   */
  static readonly POSITION: number = 1;

  /**
   * The interval time of Swiper.
   */
  static readonly TIME: number = 4000;

  /**
   * The duration of Swiper.
   */
  static readonly DURATION: number = 1000;

  /**
   * The item space of Swiper.
   */
  static readonly ITEM_SPACE: number = 0;
};

/**
 * The constant of GoodsComponent.
 */
export class GoodsList {
  /**
   * The padding of grid.
   */
  static readonly GRID_PADDING: number = 12;

  /**
   * The columnsGap of grid.
   */
  static readonly SPACE: number = 8;


  /**
   * The layout direction of grid.
   */
  static readonly HORIZONTAL: number = 0;

  /**
   * The columns template of grid.
   */
  static readonly GRID_STYLE: string = '1fr 1fr';
};

/**
 * The constant of GoodsItemComponent.
 */
export class GoodsListItem {
  /**
   * The container height of goods name.
   */
  static readonly CONTAINER_GOODS_NAME_HEIGHT: number = 40;

  /**
   * The max line of goods name.
   */
  static readonly MAX_LINE_GOODS_NAME: number = 2;

  /**
   * The margin of goods discounts.
   */
  static readonly MARGIN_DISCOUNTS: number = 5;

  /**
   * The size of goods image.
   */
  static readonly GOODS_IMAGE_SIZE: number = 130;

  /**
   * The top margin of goods image.
   */
  static readonly GOODS_IMAGE_MARGIN_TOP: number = 10;

  /**
   * The border radius of goods label.
   */
  static readonly BORDER_RADIUS_LABEL: number = 5;

  /**
   * The verical padding of goods label.
   */
  static readonly PADDING_LABEL_VERTICAL: number = 8;

  /**
   * The horizontal padding of goods label.
   */
  static readonly PADDING_LABEL_HORIZONTAL: number = 2;

  /**
   * The top margin of goods label container.
   */
  static readonly CONTAINER_LABEL_MARGIN_TOP: number = 6;

  /**
   * The bottom margin of goods label container.
   */
  static readonly CONTAINER_LABEL_MARGIN_BOTTOM: number = 12;

  /**
   * The top margin of text container.
   */
  static readonly TEXT_LAYER_MARGIN_TOP: number = 20;

  /**
   * The width of text container.
   */
  static readonly TEXT_LAYER_WIDTH: string = "98%";

  /**
   * The horizontal padding of item.
   */
  static readonly ITEM_PADDING_HORIZONTAL: number = 10;

  /**
   * The width of border.
   */
  static readonly BORDER_WIDTH: number = 1;

  /**
   * The value of border radius.
   */
  static readonly BORDER_RADIUS: number = 10;
};

/**
 * The constant of TabsComponent.
 */
export class GoodsTabs {
  /**
   * The height of GoodsTabs.
   */
  static readonly BAR_HEIGHT: number = 50;

  /**
   * The default index of GoodsTabs.
   */
  static readonly TABVIEW_POSITION_INDEX_PAGE: number = 0;

  /**
   * The width of image.
   */
  static readonly IMAGE_SIZE_WIDTH: number = 12;

  /**
   * The height of image.
   */
  static readonly IMAGE_SIZE_HEIGHT: number = 16;


  /**
   * The width of tab.
   */
  static readonly TAB_WIDTH: string = '90%';

  /**
   * The animation duration of Tabs.
   */
  static readonly TIME: number = 400;

  /**
   * The blank width of Tabs setting.
   */
  static readonly SETTING_BLANK_WIDTH: number = 4;

  /**
   * The layout weight of Tabs setting.
   */
  static readonly SETTING_LAYOUT: string = '10%';

  /**
   * The padding of right.
   */
  static readonly PADDING_RIGHT: string = '9%';
};

/**
 * The constant of MenusComponent.
 */
export class Menus {
  /**
   * The vertical padding of container.
   */
  static readonly CONTAINER_PADDING_VERTICAL: number = 12;

  /**
   * The vertical padding of item.
   */
  static readonly ITEM_PADDING_VERTICAL: number = 16;

  /**
   * The weight of layout.
   */
  static readonly LAYOUT_WEIGHT: string = '25%';
};

/**
 * The constant of SearchComponent.
 */
export class SearchBar {
  /**
   * The width of layout.
   */
  static readonly WEIGHT: string = '90%';

  /**
   * The size of image.
   */
  static readonly IMAGE_SIZE: number = 20;

  /**
   * The height of SearchBar.
   */
  static readonly BAR_HEIGHT: number = 40;

  /**
   * The right margin of input.
   */
  static readonly TEXT_INPUT_MARGIN_RIGHT: number = 20;

  /**
   * The left padding of container.
   */
  static readonly CONTAINER_PADDING_LEFT: number = 10;

  /**
   * The border radius.
   */
  static readonly BORDER_RADIUS: number = 36;
};

/**
 * The constant of TopBarComponent.
 */
export class TopBar {
  /**
   * The size of image.
   */
  static readonly IMAGE_SIZE: number = 30;

  /**
   * The height of BalanceComponent.
   */
  static readonly HEIGHT: string = '4%';
};












